### ISSUE TITLE
Restart Warning

### ISSUE THREAD

**Issue by Sikksens** [zkkng/Zomboid_Mod_Checker#1]
Been having issues with people not being able to connect to my server because of new mod versions on clients, this is exactly what I'm looking for, would it be possible to send a 5min warning to the server before it restarts for any mod updates?

**Comment by zkkng** [comment]
I would look into https://github.com/quarantin/pz-server-tools

My script is really close to working but it doesn't 100% function yet. I think the biggest issue was that the python script doesn't re-run itself after it initiates a restart. I could probably fix it eventually but I have no clue when or if I will. I mostly wrote it to get myself back into the basics of Python.

If you happen to be running a Windows server, consider moving to Linux so you can use the project I mentioned above. If thats absolutely not an option let me know, and I will more heavily consider getting this working.

**Comment by Sikksens** [comment]
Thanks for getting back to me so soon, I'm on Linux so that's perfect, will def be using that from now on, thanks again :)
